name: 'Exchange Info Bot'

on:
  schedule:
    - cron: '*/30 * * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Push Exchange Info'
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          COIN_LIST: ${{ secrets.COIN_LIST }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          sudo apt install python3 python3-pip -y
          pip3 install requests ciso8601 python-telegram-bot
          python3 main.py
